import 'dart:ui';
import 'package:flutter/material.dart';
import '../../core/app_export.dart';

/// Helper class for managing themes and colors.
class ThemeHelper {
  // The current app theme
  var _appTheme = PrefUtils().getThemeData();

// A map of custom color themes supported by the app
  Map<String, PrimaryColors> _supportedCustomColor = {
    'primary': PrimaryColors(),
    'secondary': SecondaryColors()
  };

// A map of color schemes supported by the app
  Map<String, ColorScheme> _supportedColorScheme = {
    'primary': ColorSchemes.primaryColorScheme,
    'secondary': ColorSchemes.secondaryColorScheme
  };

  /// Returns the primary colors for the current theme.
  PrimaryColors _getThemeColors() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedCustomColor.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    return _supportedCustomColor[_appTheme] ?? PrimaryColors();
  }

  /// Returns the current theme data.
  ThemeData _getThemeData() {
    //throw exception to notify given theme is not found or not generated by the generator
    if (!_supportedColorScheme.containsKey(_appTheme)) {
      throw Exception(
          "$_appTheme is not found.Make sure you have added this theme class in JSON Try running flutter pub run build_runner");
    }
    //return theme from map

    var colorScheme =
        _supportedColorScheme[_appTheme] ?? ColorSchemes.primaryColorScheme;
    return ThemeData(
      visualDensity: VisualDensity.standard,
      colorScheme: colorScheme,
      textTheme: TextThemes.textTheme(colorScheme),
      scaffoldBackgroundColor: appTheme.whiteA700,
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: appTheme.teal200,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(13.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
      outlinedButtonTheme: OutlinedButtonThemeData(
        style: OutlinedButton.styleFrom(
          backgroundColor: Colors.transparent,
          side: BorderSide(
            color: appTheme.lightBlue900,
            width: 1.h,
          ),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10.h),
          ),
          visualDensity: const VisualDensity(
            vertical: -4,
            horizontal: -4,
          ),
          padding: EdgeInsets.zero,
        ),
      ),
    );
  }

  /// Returns the primary colors for the current theme.
  PrimaryColors themeColor() => _getThemeColors();

  /// Returns the current theme data.
  ThemeData themeData() => _getThemeData();
}

/// Class containing the supported text theme styles.
class TextThemes {
  static TextTheme textTheme(ColorScheme colorScheme) => TextTheme(
        bodyLarge: TextStyle(
          color: appTheme.lightBlueA700,
          fontSize: 17.fSize,
          fontFamily: 'SF Pro Text',
          fontWeight: FontWeight.w400,
        ),
        bodyMedium: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 15.fSize,
          fontFamily: 'Magra',
          fontWeight: FontWeight.w400,
        ),
        bodySmall: TextStyle(
          color: appTheme.lightBlue900,
          fontSize: 12.fSize,
          fontFamily: 'Lexend Exa',
          fontWeight: FontWeight.w400,
        ),
        displayMedium: TextStyle(
          color: colorScheme.errorContainer.withOpacity(1),
          fontSize: 48.fSize,
          fontFamily: 'Lexend Exa',
          fontWeight: FontWeight.w400,
        ),
        displaySmall: TextStyle(
          color: appTheme.black900,
          fontSize: 36.fSize,
          fontFamily: 'Lobster Two',
          fontWeight: FontWeight.w400,
        ),
        headlineSmall: TextStyle(
          color: colorScheme.errorContainer.withOpacity(1),
          fontSize: 24.fSize,
          fontFamily: 'Lexend Exa',
          fontWeight: FontWeight.w400,
        ),
        labelLarge: TextStyle(
          color: colorScheme.errorContainer.withOpacity(1),
          fontSize: 12.fSize,
          fontFamily: 'Lexend Exa',
          fontWeight: FontWeight.w700,
        ),
        titleLarge: TextStyle(
          color: colorScheme.primaryContainer,
          fontSize: 20.fSize,
          fontFamily: 'Lobster Two',
          fontWeight: FontWeight.w400,
        ),
        titleMedium: TextStyle(
          color: colorScheme.errorContainer.withOpacity(1),
          fontSize: 17.fSize,
          fontFamily: 'SF Pro Text',
          fontWeight: FontWeight.w600,
        ),
        titleSmall: TextStyle(
          color: colorScheme.onPrimary,
          fontSize: 15.fSize,
          fontFamily: 'Magra',
          fontWeight: FontWeight.w600,
        ),
      );
}

/// Class containing the supported color schemes.
class ColorSchemes {
  static final primaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF1BC440),
    primaryContainer: Color(0XFF6000FF),
    secondaryContainer: Color(0XFFD71A1A),

    // Error colors
    errorContainer: Color(0X3F000000),
    onError: Color(0XFF979797),

    // On colors(text colors)
    onPrimary: Color(0XFF2300FD),
    onPrimaryContainer: Color(0XFFD9D9D9),
  );

  static final secondaryColorScheme = ColorScheme.light(
    // Primary colors
    primary: Color(0XFF1BC440),
    primaryContainer: Color(0XFF6000FF),
    secondaryContainer: Color(0XFFD71A1A),

    // Error colors
    errorContainer: Color(0X3F000000),
    onError: Color(0XFF979797),

    // On colors(text colors)
    onPrimary: Color(0XFF2300FD),
    onPrimaryContainer: Color(0XFFD9D9D9),
  );
}

/// Class containing custom colors for a primary theme.
class PrimaryColors {
  // Amber
  Color get amber600 => Color(0XFFFFB700);

  // Black
  Color get black900 => Color(0XFF000000);

  // DeepPurple
  Color get deepPurpleA700 => Color(0XFF2300FD);

  // Gray
  Color get gray200 => Color(0XFFF0F0F0);
  Color get gray500 => Color(0XFF979797);
  Color get gray900 => Color(0XFF282424);

  // GrayEf
  Color get gray50Ef => Color(0XEFF9F9F9);

  // Green
  Color get greenA700 => Color(0XFF1BC440);

  // LightBlue
  Color get lightBlue900 => Color(0XFF02458D);
  Color get lightBlueA700 => Color(0XFF007AFF);

  // LightGreen
  Color get lightGreenA700 => Color(0XFF58E435);

  // Red
  Color get redA700 => Color(0XFFFF0000);

  // Teal
  Color get teal200 => Color(0XFF8CB9CD);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

/// Class containing custom colors for a secondary theme.
class SecondaryColors extends PrimaryColors {
  // Amber
  Color get amber600 => Color(0XFFFFB700);

  // Black
  Color get black900 => Color(0XFF000000);

  // DeepPurple
  Color get deepPurpleA700 => Color(0XFF2300FD);

  // Gray
  Color get gray200 => Color(0XFFF0F0F0);
  Color get gray500 => Color(0XFF979797);
  Color get gray900 => Color(0XFF282424);

  // GrayEf
  Color get gray50Ef => Color(0XEFF9F9F9);

  // Green
  Color get greenA700 => Color(0XFF1BC440);

  // LightBlue
  Color get lightBlue900 => Color(0XFF02458D);
  Color get lightBlueA700 => Color(0XFF007AFF);

  // LightGreen
  Color get lightGreenA700 => Color(0XFF58E435);

  // Red
  Color get redA700 => Color(0XFFFF0000);

  // Teal
  Color get teal200 => Color(0XFF8CB9CD);

  // White
  Color get whiteA700 => Color(0XFFFFFFFF);
}

PrimaryColors get appTheme => ThemeHelper().themeColor();
ThemeData get theme => ThemeHelper().themeData();
